### ISSUE TITLE
Access to edit

### ISSUE THREAD

**Issue by biskyt** [AppertaFoundation/eyedraw-website#1]
Hi Marcus, Could our developers get access to upload new in-development doodles to the site? Let me know your preferred approach.

Thanks

**Comment by pacharanero** [comment]
Hi Toby,

Yes happy to add your developers.

Who do I need to add and I'll give them write access to the repo

M

**Comment by biskyt** [comment]
If you could add sabi1981 for now that would be great.

BTW - I've noticed that eyedraw does already include a selection of test-harnesses at [tests/other](https://github.com/AppertaFoundation/eyedraw/tree/release/v2.0.2/tests/other) (e.g. [test/other/alldoodles.html](https://github.com/AppertaFoundation/eyedraw/blob/release/v2.0.2/tests/other/AllDoodles.html)). I'd like to extend these at some point to also include all canvases, the reports and side-views. Then these can be used in place of (or in addition to) this site as it stands currently.

**Comment by pacharanero** [comment]
Ok I've created a team for access to this repo:

https://github.com/orgs/AppertaFoundation/teams/abehr-openeyes-eyedraw/members

I've added biskyt and sabi1981

I've made this team have Write access to both repos

And I've promoted Toby to be a maintainer of that team, so you can manage
the membership as required.

How's that for ya? ;-)

M

**Comment by biskyt** [comment]
@pacharanero - Any chance you could add mscross92 to the team? I don't have permission to do so (it tells me she isn't a member of the organization - and I don't have permissions to add people to the org). Thanks

**Comment by pacharanero** [comment]
done

**Comment by biskyt** [comment]
Thanks
