### ISSUE TITLE
Rename repo/site?

### ISSUE THREAD

**Issue by biskyt** [AppertaFoundation/eyedraw-website#2]
Having this called openeyes-website is confusing (to me at least), seeing as it isn't the openeyes website, it is the eyedraw website (eyedraw being a standalone project).

Would it be possible to rename to eyedraw-website?

**Comment by pacharanero** [comment]
OK no problem. I've changed it.

You may need to update your Git remotes

**Comment by biskyt** [comment]
Excellent. Thanks
